#!/usr/bin/env bash
# Configures a server as follows:
#   - localhost ip is 127.0.0.2
#   - faacebook.com ip is 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
